name: Publish package

on:
  push:
    branchs:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
