- name: Publish package
  if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
  uses: pypa/gh-action-pypi-publish@release/v1
  with:
    password: ${{ secrets.PYPI_API_TOKEN }}
